Study class format edited and worked on #8
alexhan46/studyfind-ai-web-crawler pull request #13
Opened 2020-09-18 04:30 UTC by joheeju

1. Study class
- Matched all variables with lower_case_with_underscores
- Changed some format of arguments (For example, contact, age, etc) according to raw data

2. #8  
- Worked on almost everything except some vague parts (will discuss during meeting on 9/18)

2020-09-18 14:40 UTC, adeeb897 commented
What is BeautifulSoup? If that's from a package, we should start a requirements.txt with this pull request to keep track of packages and make them easier to install.

2020-09-18 14:45 UTC, adeeb897 commented
Also, are there other packages I need to install, because I'm not able to run this code

2020-09-18 14:48 UTC, jkim3389 commented
> What is BeautifulSoup? If that's from a package, we should start a requirements.txt with this pull request to keep track of packages and make them easier to install.

its crawling tool so that you can scrap the website easily

2020-09-18 14:53 UTC, adeeb897 commented
> > What is BeautifulSoup? If that's from a package, we should start a requirements.txt with this pull request to keep track of packages and make them easier to install.
> 
> its crawling tool so that you can scrap the website easily

So we have to install it using pip? What's the package name

2020-09-18 14:54 UTC, jkim3389 commented
> > > What is BeautifulSoup? If that's from a package, we should start a requirements.txt with this pull request to keep track of packages and make them easier to install.
> > 
> > 
> > its crawling tool so that you can scrap the website easily
> 
> So we have to install it using pip? What's the package name

Yeap so what I installed is
pip3 install BeautifulSoup4
pip3 install requests
pip3 install lxml

2020-09-18 15:01 UTC, adeeb897 commented
> > > > What is BeautifulSoup? If that's from a package, we should start a requirements.txt with this pull request to keep track of packages and make them easier to install.
> > > 
> > > 
> > > its crawling tool so that you can scrap the website easily
> > 
> > 
> > So we have to install it using pip? What's the package name
> 
> Yeap so what I installed is
> pip3 install BeautifulSoup4
> pip3 install requests
> pip3 install lxml
> 
> and in code
> from bs4 import BeautifulSoup to use it

Are you able to run the code after that? I'm still getting compilation errors.

Also we should something like this
`beautifulsoup4==4.9.1
lxml==4.5.2
requests==2.24.0
urllib3==1.25.10
`
into a requirements.txt then we can just do `pip install -r requirements.txt`

2020-09-18 16:02 UTC, adeeb897 requested changes
I wasn't able to compile your code, but I think I noticed all of the compilation errors. Were you able to compile and run your code?

2020-09-18 16:02 UTC, adeeb897 commented on crawler.py
> +        self.recruitment_status = recruitmentStatus
`recruitmentStatus` needs to be `recruitment_status`

2020-09-18 16:02 UTC, adeeb897 commented on crawler.py
> +        self.additional_criteria = additionalCriteria
`additionalCriteria` needs to be `additional_criteria`

2020-09-18 16:02 UTC, adeeb897 commented on crawler.py
> +import urllib.request
I think we need to add import?
`from bs4 import BeautifulSoup`

2020-09-18 17:13 UTC, adeeb897 requested changes

2020-09-18 17:13 UTC, adeeb897 commented on crawler.py
> +        self.recruitment_status = recruitment_Status
`recruitment_status`

2020-09-18 18:39 UTC, adeeb897 requested changes
The changes look good, it's compiling for me! There are some parts causing run-time errors though. but you might have not seen these errors since I tested them on random studies. We should be able to fully test this code next week for similar errors.

I commented on which lines caused problems, once those are fixed we should be good!

By the way you can test your code by doing something like
`
s = download_and_format("NCT04554966")`
`print(vars(s))
`
at the very bottom and then running the python script

2020-09-18 18:39 UTC, adeeb897 commented on crawler.py
> +    control = data.find("healthy_volunteers").get_text()
This part caused an error when I tested your code on  random studies. I recommend doing this


```suggestion
try:
       control = data.find("healthy_volunteers").get_text()
except AttributeError:
       control = None
```

2020-09-18 18:39 UTC, adeeb897 commented on crawler.py
> +            locations.append({"locationLocation": localLocation, "nationalLocation": nationalLocation, "status": status})
The status part also caused an error, do we need it? maybe we can do something like this
```suggestion
            locations.append({"locationLocation": localLocation, "nationalLocation": nationalLocation})
```

2020-09-21 16:48 UTC, adeeb897 reviewed
Looks good!

2020-09-21 16:51 UTC, adeeb897 approved these changes

2020-09-21 16:59 UTC, merged